apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-nodejs-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      type: frontend   # NodeJS pods
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              type: backend   # MongoDB
      ports:
        - protocol: TCP
          port: 27017
