kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: s2i-build
  namespace: nav220161-dev
  uid: 2ff5f59c-3aa9-440f-a0b3-7e420fd60e3c
  resourceVersion: '5261924817'
  generation: 7
  creationTimestamp: '2025-11-20T05:42:07Z'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-build:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'ruby:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ruby-ex.git'
      ref: master
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
