apiVersion: v1
kind: Pod
metadata:
  name: pod-noexecute
spec:
  tolerations:
    - key: "env"
      operator: "Equal"
      value: "dev"
      effect: "NoExecute"
  containers:
    - name: nginx
      image: nginx